import { ThemeProvider } from "@/context/theme-provider";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-screen flex justify-center items-center w-full py-6">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
