export const assignmentData = [
  {
    id: 1,
    module: "Introduction to Python",
    created_at: "10 May 2024",
    dateline: "20 May 2024",
    title: "Intro TO web",
    file: "Assignment 1",
  },
  {
    id: 2,
    module: "Java Programming",
    created_at: "16 May 2024",
    dateline: "26 May 2024",
    title: "Intro TO web",
    file: "Assignment 2",
  },
  {
    id: 3,
    module: "Data Structures",
    created_at: "20 May 2024",
    dateline: "30 May 2024",
    title: "Intro TO web",
    file: "Assignment 3",
  },
  {
    id: 4,
    module: "Web Development",
    created_at: "25 May 2024",
    dateline: "05 June 2024",
    title: "Intro TO web",
    file: "Assignment 4",
  },
  {
    id: 5,
    module: "Database Management",
    created_at: "30 May 2024",
    dateline: "10 June 2024",
    title: "Intro TO web",
    file: "Assignment 5",
  },
  {
    id: 6,
    module: "JavaScript Programming ",
    created_at: "05 June 2024",
    dateline: "15 June 2024",
    title: "Intro TO web",
    file: "Assignment 6",
  },
  {
    id: 7,
    module: "React JS",
    created_at: "10 June 2024",
    dateline: "20 June 2024",
    title: "Intro TO web",
    file: "Assignment 7",
  },
];
